import Header from "@/components/Header";
import Hero from "@/components/Hero";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>{`Akshay's Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* hero */}
      <section id="hero" className="snap-center">
        <Hero />
      </section>
      {/* about */}
      {/* experience */}
      {/* skills */}
      {/* project */}
    </div>
  );
}

// https://www.youtube.com/watch?v=urgi2iz9P6U 1 hour 12 min
